[package]
name = "neovide-tabs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
image = { version = "0.24.9", default-features = false, features = ["png"] }
libghostty-vt = "0.2.0"
macroquad = "0.4.15"
portable-pty = "0.9.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.8.23"

[lints.rust]
rust_2018_idioms = "deny"
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
too_many_lines = "deny"
undocumented_unsafe_blocks = "deny"
unimplemented = "deny"
